baseURL = "https://piotrromanowski.github.io/"
title = "Piotr Romanowski"
languageCode = "en-us"
theme = "hugo-natrium-theme"
pygmentsStyle = "monokai"

[[menu.main]]
    name = "Home"
    url = "/"

[[menu.main]]
    title = "Photography"
    name = "Photography"
    url = "/page/photography"
    weight = -120

[[menu.main]]
    title = "About"
    name = "About"
    url = "/page/about"
    weight = -110