baseURL = "https://piotrromanowski.github.io/"
languageCode = "en-us"
title = "piotr.codes"
theme = "hugo-natrium-theme"
pygmentsStyle = "monokai"

[[menu.main]]
    name = "Home"
    url = "/"

[[menu.main]]
    name = "About"
    url = "/page/about"
